# Site
repository: mihaialexandruteodor/teo_mihai_portfolio
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Alexandru-Teodor Mihai
title: Software Developer
#email: Your email (optional)
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  mihaialexandruteodor
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: teodor-mihai-5294b01b3
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpeg
about_content: With four years of experience in software development, I have a proven track record of delivering high-quality software solutions on time and within budget. I am skilled in a wide range of programming languages and technologies, including Java, Python, Angular, .N am constantly learninet C#, SQL, and REST APIs, and Ig and keeping up-to-date with the latest trends and advancements in the field.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Feather Writer
        link: https://github.com/mihaialexandruteodor/FeatherWriter
        link_text: Repo
        quote: >
          Cloud Native Novel Writing Software.
        description: | # this will include new lines to allow paragraphs
          The application  was developed from the desire to create a Cloud Native service with the features of managing and organizing the information and content of a novel, found in software products such as Scrivener, with the benefit of being free, supporting integration with browser plugins. and adhering to Open Source principles that allow code redistribution and modification.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: UniPad
        link: https://github.com/mihaialexandruteodor/UniPad
        link_text: Repo
        quote: >
          iOS app for taking notes with OCR text recognition.
        description: | # this will include new lines to allow paragraphs
          OS app for taking quick notes using the camera and saving them as PDF, along with the OCR recognition of the text detected.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Unibuc Routing App
        link: https://github.com/mihaialexandruteodor/UniBuc-Routing-App
        link_text: Repo
        quote: >
          Android maps app that helps University of Bucharest students.
        description: | # this will include new lines to allow paragraphs
          Android app that uses OpenStreetMaps OSMDroid SDK and Firebase to help University of Bucharest students find all campus buildings within the city.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Ubuntu Regolith Configurator
        link: https://github.com/mihaialexandruteodor/Ubuntu-Regolith-Configurator
        link_text: Repo
        quote: >
          Script for a quick Ubuntu configuration with apps and i3 window manager.
        description: | # this will include new lines to allow paragraphs
          After a fresh install, you can run this script with cURL to not only install the i3 tiling window manager, but to also pick from a list of apps to be automatically installed. 
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Technohub
        sub_title: Software Developer
        caption: May 2023 - present
        link: https://www.technohub.ro/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Skills: HTML5 · Angular · Cascading Style Sheets (CSS) · .NET Framework · Microsoft SQL Server · Xamarin · Microsoft Report Builder
      - layout: left
        title: Luxoft
        sub_title: Frontend Developer
        caption: July 2022 - May 2023
        link: https://career.luxoft.com/locations/romania/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Skills: React.js · Cascading Style Sheets (CSS) · JavaScript
      - layout: left
        title: Oracle
        sub_title: Staff Consultant
        caption: October 2021 - July 2022
        link: https://www.oracle.com/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Skills: Grafana · InfluxDB · Shell Scripting · Docker · Python · SQL
      - layout: left
        title: Fan Courier
        sub_title: Junior Software Developer
        caption: Date Range (eg. November 2016 - present)
        link: https://www.fancourier.ro/en/home/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Skills: Visual Basic · .NET Framework · Microsoft SQL Server
      - layout: left
        title: Magic Lane
        sub_title: Project Support Programmer
        caption: July 2019 - June 2020
        link: https://www.magiclane.com/web/
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Skills: Java · Kotlin · C++
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: University of Bucharest
        sub_title: Master's Degree - Software Engineering
        caption: 2020 - 2022
        quote: >
          Graduated with a 9.5/10 on my final project.
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
      - layout: top-left
        title: Transylvania University of Brasov
        sub_title: Bachelor's Degree - Computer Science
        caption: 2017 - 2020
        quote: >
          Graduated with a 10/10 on my final project.
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love to write, draw and read in my free time. I am a great lover of cinema (particularly the Korean films of Bong Joon-Ho and Park Chan-Wook), and my favorite film is The Matrix. I love to read Manga and listen to movie scores.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
